version: "3"

services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:12.9.7-ce.0
    restart: always
    networks:
      - traefik
    ports:
      - '10022:22'
    expose:
      - "80"
      - "5005"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        ## GitLab configuration settings
        ##! Check out the latest version of this file to know about the different
        ##! settings that can be configured by this file, which may be found at:
        ##! https://gitlab.com/gitlab-org/omnibus-gitlab/raw/master/files/gitlab-config-template/gitlab.rb.template

        ## GitLab URL
        ##! URL on which GitLab will be reachable.
        ##! For more details on configuring external_url see:
        ##! https://docs.gitlab.com/omnibus/settings/configuration.html#configuring-the-external-url-for-gitlab
        external_url 'GENERATED_EXTERNAL_URL'


        ################################################################################
        ################################################################################
        ##                Configuration Settings for GitLab CE and EE                 ##
        ################################################################################
        ################################################################################

        ################################################################################
        ## gitlab.yml configuration
        ##! Docs: https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/doc/settings/gitlab.yml.md
        ################################################################################
        gitlab_rails['gitlab_ssh_host'] = 'ssh.gitlab.domain.com'
        gitlab_rails['time_zone'] = 'UTC'


        ### Email Settings
        gitlab_rails['gitlab_email_enabled'] = true
        gitlab_rails['gitlab_email_from'] = 'example@domain.com'
        gitlab_rails['gitlab_email_display_name'] = 'Example'
        gitlab_rails['gitlab_email_reply_to'] = 'noreply@domain.com'
        gitlab_rails['gitlab_email_subject_suffix'] = ''


        ### Default project feature settings
        gitlab_rails['gitlab_default_projects_features_issues'] = true
        gitlab_rails['gitlab_default_projects_features_merge_requests'] = true
        gitlab_rails['gitlab_default_projects_features_wiki'] = true
        gitlab_rails['gitlab_default_projects_features_snippets'] = true
        gitlab_rails['gitlab_default_projects_features_builds'] = true
        gitlab_rails['gitlab_default_projects_features_container_registry'] = true

        ### Backup Settings
        ###! Docs: https://docs.gitlab.com/omnibus/settings/backups.html

        gitlab_rails['manage_backup_path'] = true
        gitlab_rails['backup_path'] = "/var/opt/gitlab/backups"

        ###! Docs: https://docs.gitlab.com/ce/raketasks/backup_restore.html#backup-archive-permissions
        gitlab_rails['backup_archive_permissions'] = 0644

        # gitlab_rails['backup_pg_schema'] = 'public'

        ###! The duration in seconds to keep backups before they are allowed to be deleted
        # gitlab_rails['backup_keep_time'] = 604800

        # gitlab_rails['backup_upload_connection'] = {
        #   'provider' => 'AWS',
        #   'region' => 'eu-west-1',
        #   'aws_access_key_id' => 'AKIAKIAKI',
        #   'aws_secret_access_key' => 'secret123'
        # }
        # gitlab_rails['backup_upload_remote_directory'] = 'my.s3.bucket'
        # gitlab_rails['backup_multipart_chunk_size'] = 104857600

        ###! **Turns on AWS Server-Side Encryption with Amazon S3-Managed Keys for
        ###!   backups**
        # gitlab_rails['backup_encryption'] = 'AES256'

        ###! **Specifies Amazon S3 storage class to use for backups. Valid values
        ###!   include 'STANDARD', 'STANDARD_IA', and 'REDUCED_REDUNDANCY'**
        # gitlab_rails['backup_storage_class'] = 'STANDARD'


        ### GitLab email server settings
        ###! Docs: https://docs.gitlab.com/omnibus/settings/smtp.html
        ###! **Use smtp instead of sendmail/postfix.**

        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.server"
        gitlab_rails['smtp_port'] = 465
        gitlab_rails['smtp_user_name'] = "smtp user"
        gitlab_rails['smtp_password'] = "smtp password"
        gitlab_rails['smtp_domain'] = "domain.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = false

        ### LDAP Settings
        ###! Docs: https://docs.gitlab.com/omnibus/settings/ldap.html
        ###! **Be careful not to break the indentation in the ldap_servers block. It is
        ###!   in yaml format and the spaces must be retained. Using tabs will not work.**

        # gitlab_rails['ldap_enabled'] = false

        ###! **remember to close this block with 'EOS' below**
        # gitlab_rails['ldap_servers'] = YAML.load <<-'EOS'
        #   main: # 'main' is the GitLab 'provider ID' of this LDAP server
        #     label: 'LDAP'
        #     host: '_your_ldap_server'
        #     port: 389
        #     uid: 'sAMAccountName'
        #     bind_dn: '_the_full_dn_of_the_user_you_will_bind_with'
        #     password: '_the_password_of_the_bind_user'
        #     encryption: 'plain' # "start_tls" or "simple_tls" or "plain"
        #     verify_certificates: true
        #     active_directory: true
        #     allow_username_or_email_login: false
        #     lowercase_usernames: false
        #     block_auto_created_users: false
        #     base: ''
        #     user_filter: ''
        #     ## EE only
        #     group_base: ''
        #     admin_group: ''
        #     sync_ssh_keys: false
        #
        #   secondary: # 'secondary' is the GitLab 'provider ID' of second LDAP server
        #     label: 'LDAP'
        #     host: '_your_ldap_server'
        #     port: 389
        #     uid: 'sAMAccountName'
        #     bind_dn: '_the_full_dn_of_the_user_you_will_bind_with'
        #     password: '_the_password_of_the_bind_user'
        #     encryption: 'plain' # "start_tls" or "simple_tls" or "plain"
        #     verify_certificates: true
        #     active_directory: true
        #     allow_username_or_email_login: false
        #     lowercase_usernames: false
        #     block_auto_created_users: false
        #     base: ''
        #     user_filter: ''
        #     ## EE only
        #     group_base: ''
        #     admin_group: ''
        #     sync_ssh_keys: false
        # EOS

        ################################################################################
        ## GitLab Nginx
        ##! Docs: https://docs.gitlab.com/omnibus/settings/nginx.html
        ################################################################################

        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['proxy_set_headers'] = {
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        }

        ################################################################################
        ## Container Registry settings
        ##! Docs: https://docs.gitlab.com/ce/administration/container_registry.html
        ################################################################################

        registry_external_url 'https://registry.domain.com'

        ### Settings used by GitLab application
        gitlab_rails['registry_enabled'] = true
        gitlab_rails['registry_host'] = "registry.domain.com"
        gitlab_rails['registry_port'] = "5005"
        gitlab_rails['registry_path'] = "/var/opt/gitlab/gitlab-rails/shared/registry"

        ################################################################################
        ## Registry NGINX
        ################################################################################

        registry_nginx['listen_port'] = 5005
        registry_nginx['listen_https'] = false
        registry_nginx['proxy_set_headers'] = {
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        }

    volumes:
      - config:/etc/gitlab
      - logs:/var/log/gitlab
      - data:/var/opt/gitlab
      - mnt:/mnt
    labels:
      # Dynamic configuration with Docker Labels
      # Ref: https://docs.traefik.io/reference/dynamic-configuration/docker/
      - "traefik.enable=true"
      - "traefik.http.routers.gitlab.entrypoints=web"
      - "traefik.http.routers.gitlab.rule=Host(`gitlab.domain.com`)"
      - "traefik.http.routers.gitlab.service=gitlab"
      - "traefik.http.services.gitlab.loadbalancer.server.port=80"
      - "traefik.http.routers.gitlab-registry.entrypoints=web"
      - "traefik.http.routers.gitlab-registry.rule=Host(`registry.domain.com`)"
      - "traefik.http.routers.gitlab-registry.service=gitlab-registry"
      - "traefik.http.services.gitlab-registry.loadbalancer.server.port=80"

volumes:
  config: {}
  logs: {}
  data: {}
  mnt: {}

networks:
  traefik:
    external: true
